import { Product } from './product';

export const  PRODUCTS: Product[]= [
  {
    id:1,
    name: 'White Dial Rose Gold & Grey Watch',
    price: '97,83$',
    description: 'Olivia Burton Midi Dial OB16MDW05 is an amazing and trendy Ladies watch.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100000056/main/large/ob16mdw05-1475843448-9719.jpg'],
    categoryId:2,
    plink:'',
    sale: false,
  },
  {
    id:2,
    name: 'Mother Of Pearl Bracelet Silver Watch',
    price: '122,60$',
    description: 'Case material is Stainless Steel and the Mother of pearl dial gives the watch that unique look.',
    Image:['https://d1rkccsb0jf1bk.cloudfront.net/products/100026749/main/large/MED_SILVER_BRACELET_OB16MOP02_1.jpg'],
    categoryId:2,
    plink:'',
    sale: false,
  },
  {
    id:3,
    name: 'Tommy Hilfiger Watch 1791615',
    price: '185,75$',
    description: 'Tommy Hilfiger Shawn 1791615 is a practical and special Gents watch.Case material is Stainless Steel while the dial colour is Grey',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100037385/main/large/1791615_LRG_rgb_Web.jpg'],
    categoryId:1,
    plink:'',
    sale: false,
  },
  {
    id:4,
    name: 'Swiss Military Hanowa Watch',
    price: '382,65$',
    description: 'Swiss Military Hanowa Chrono Classic 06-5332.04.003 is a functional and special Gents watch. Material of the case is Stainless Steel and the Navy dial gives the watch that unique look.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100036869/main/large/6533204003.jpg'],
    categoryId:1,
    plink:'',
    sale: false,
  },
  {
    id:5,
    name: 'STORM Watch 47466/B',
    price: '173,36$',
    description: 'STORM 47466/B is a practical and very impressive Gents watch. Case material is Stainless Steel and the Blue dial gives the watch that unique look.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100037281/main/large/KOMBITRON_IP-BLUE.jpg'],
    categoryId:1,
    plink:'',
    sale: false,
  },
  {
    id:6,
    name: 'Fossil Watch BQ2465SET',
    price: '112,69$',
    description: 'Fossil LEDGER BQ2465SET is an amazing and handsome Gents watch. Material of the case is Stainless Steel while the dial colour is Black.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100036975/main/large/BQ2465SET_main.jpg'],
    categoryId:1,
    plink:'',
    sale: false,
  },
  {
    id:7,
    name: 'Fossil Watch BQ2446',
    price: '122,60$',
    description: 'he features of the watch include (among others) a chronograph. This model has got 50 metres water resistancy.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100036974/main/large/BQ2446_main.jpg'],
    categoryId:1,
    plink:'',
    sale: false,
  },
  {
    id:8,
    name: 'Certina Watch C0144101605100',
    price: '386,37$',
    description: '200 metres water resistancy will protect the watch and allows it to be used for professional marine activity, skin diving and high impact water sports.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100036937/main/large/C0144101605100.jpg'],
    categoryId:1,
    plink:'',
    sale: true,
  },
  {
    id:9,
    name: 'Timex Watch TW2U22200',
    price: '86,67$',
    description: 'Material of the case is Brass plated and the White dial gives the watch that unique look.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100037073/main/large/TW2U22200.jpg'],
    categoryId:1,
    plink:'',
    sale: false,
  },
  {
    id:10,
    name: 'Tommy Hilfiger Watch 1782129',
    price: '185,75$',
    description: 'In regards to the water resistance, the watch has got a resistancy up to 30 metres.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100037388/main/large/1782129_LRG_rgb_Web.jpg'],
    categoryId:1,
    plink:'',
    sale: false,
  },
  {
    id:11,
    name: 'Tommy Hilfiger Watch 1782030',
    price: '185,75$',
    description: 'Tommy Hilfiger Jenna 1782030 is an incredible interesting Ladies watch. Case is made out of Stainless Steel while the dial colour is Pink.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100037386/main/large/1782030_LRG_rgb_Web.jpg'],
    categoryId:1,
    plink:'',
    sale: false,
  },
  {
    id:12,
    name: 'Michael Kors Watch MK3853',
    price: '203,09$',
    description: 'Michael Kors PORTIA MK3853 is a beautiful and attractive Ladies watch from LADIESMETALS collection. Material of the case is Stainless Steel.',
    Image:['https://d1rkccsb0jf1bk.cloudfront.net/products/100036978/main/large/MK3853_main.jpg'],
    categoryId:2,
    plink:'',
    sale: true,
  },
  {
    id:13,
    name: 'Ladies Michel Herbelin Equinoxe Watch',
    price: '390,08$',
    description: 'Michel Herbelin Equinoxe 17497/P29GR is an amazing and interesting Ladies watch.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100037255/main/large/17497-PR29GR.jpg'],
    categoryId:2,
    plink:'',
    sale: false,
  },
  {
    id:14,
    name: 'Ladies Guess Watch V1008M2',
    price: '110,21$',
    description: 'Guess V1008M2 is an incredible trendy Ladies watch. Material of the case is Stainless Steel, which stands for a high quality of the item.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100037273/main/large/V1008M2.jpg'],
    categoryId:2,
    plink:'',
    sale: false,
  },
  {
    id:15,
    name: 'Timex Watch TW2U22000',
    price: '86,67$',
    description: 'Timex Essential TW2U22000 is an amazing and trendy Ladies watch from Womens Easy Reader collection.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100037094/main/large/TW2U22000.jpg'],
    categoryId:2,
    plink:'',
    sale: true,
  },
  {
    id:16,
    name: 'Maurice Lacroix Watch ',
    price: '736,82$',
    description: 'Maurice Lacroix Eliros EL1118-PVP01-610-1 is a great Unisex watch from Eliros collection. Case material is Stainless Steel.',
    Image: ['https://d1rkccsb0jf1bk.cloudfront.net/products/100037269/main/large/EL1118_PVP01_610_1.jpg'],
    categoryId:2,
    plink:'',
    sale: false,
  },
  ];