# Generated by Django 3.0.4 on 2020-04-20 10:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list, max_length=1000), default=list, size=None),
            preserve_default=False,
        ),
    ]
