# Generated by Django 3.0.4 on 2020-04-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
